### ISSUE TITLE
WebSite plugin instructions update?

### ISSUE THREAD

**Issue by mvackel** [hjd1964/OnStepX-Plugins#1]
It seems that the website plugin instructions needs updating:
- When compiling, there is a message: "Configuration (Config.h): The website plugin requires SERIAL_RADIO be set to WIFI_STATION or WIFI_ACCESS_POINT" - this configuration is not mentioned.
- There is no defines "SERIAL_IP_MODE" and "WEB_SERVER ON" on the file "Extend.config.h" (and seems to be  not necessary)
- Maybe its a good idea to mention that the default wifi password is "password"

- On the website file  "config.h", the comment says that the SSID is "ONSTEP" but in reallity it is "OnStepX"

**Comment by hjd1964** [comment]
The first two issues I will not address until the main branch becomes an release.
I updated the SWS on this Plugin's Config.h comments to address the second two issues however.
Thanks.
